services:
  - type: web
    name: wakemate-backend
    plan: free
    build:
      dockerfile: Dockerfile
      # 強制 Render 使用 Python 3.11
      environment:
        python_version: 3.11.9
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: user_info_wakemate_db
          property: connectionString
    healthCheckPath: /ping