services:
  - type: cron job
    name: wakemate-cal-model
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false